version: "1.0"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql:/sql/
    environment:
      - POSTGRES_PASSWORD=postgres
    # env_file:
    #   - ./secrets/.env
    ports:
      - "5432:5432"
  token-service:
    build: token-service/.
    ports:
      - "8082:8082"
  backend:
    build: backend/.
    ports:
    - "8081:8081"
    depends_on: 
    - db
    - token-service
    - streaming-service
    - imaging-service
#  frontend:
#    build: frontend/.
#    ports:
#    - "3000:3000"
  imaging-service:
    build: imaging/.
    ports:
    - "8088:8088"
  streaming-service:
    build: streaming-service/.
    ports:
      - "8181:8181"
volumes:
  postgres_data: