version: "1.0"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql:/sql/
    environment:
      - POSTGRES_PASSWORD=postgres
    # env_file:
    #   - ./secrets/.env
    ports:
      - "5432:5432"
  redis:
      image: redis:latest
      restart: always
      ports:
        - "6379:6379"
      environment:
        - REDIS_PASSWORD=""
        - REDIS_PORT=6379
        - REDIS_DATABASES=0
  backend:
    build: backend/.
    ports:
    - "8081:8081"
    depends_on: 
    - db
  token-service:
    build: token-service/.
    depends_on: 
    - redis
    ports:
    - "8082:8082"
  frontend:
    build: frontend/.
    ports:
    - "3000:3000"
volumes:
  postgres_data:
