version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql:/sql/
      - ./docker-compose.yaml:/app/docker-compose.yaml
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  token-service:
    build: token-service/.
    volumes:
      - ./docker-compose.yaml:/app/docker-compose.yaml
    ports:
      - "8082:8082"
  backend:
    build: backend/.
#    network_mode: "host"
    ports:
      - "8081:8081"
    volumes:
      - ./docker-compose.yaml:/app/docker-compose.yaml
    depends_on: 
    - db
    - token-service
    - streaming-service
    - imaging-service
#  frontend:
#    build: frontend/.
#    depends_on:
#      - backend
#    ports:
#    - "3000:3000"
  imaging-service:
    build: imaging/.
    ports:
    - "8088:8088"
  streaming-service:
    build: streaming-service/.
    ports:
      - "8181:8181"
#  networking-service:
#    build: networking-service/.
#    network_mode: "host"
#    volumes:
#      - ./docker-compose.yaml:/app/docker-compose.yaml
volumes:
  postgres_data: