version: "1.0"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql:/sql/
    environment:
      - POSTGRES_PASSWORD=postgres
    # env_file:
    #   - ./secrets/.env
    ports:
      - "5432:5432"
  backend:
    build: backend/.
    ports:
    - "8081:8081"
    depends_on:
    - db
  frontend:
    build: frontend/.
    ports:
    - "3000:3000"
volumes:
  postgres_data: