import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { LandingFooter, LandingHeader } from '@components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<LandingHeader/>
				<div className="container">
					{children}
				</div>
				<LandingFooter/>
			</body>
		</html>
	)
}
