definitions:
  entity.GeosearchResponse:
    type: object
host: 0.0.0.0:8083
info:
  contact: {}
  description: API for Sledilka service
  termsOfService: http://swagger.io/terms/
  title: Geosearch for Sledilka API
  version: "1.0"
paths:
  /accounts:
    get:
      consumes:
      - application/json
      description: get accounts
      parameters:
      - description: name search by q
        format: email
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.GeosearchResponse'
            type: array
      summary: List accounts
      tags:
      - accounts
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Auth-Token
    scopes:
      admin: Grants read and write access to administrative information
      write: Grants write access
    type: apiKey
swagger: "2.0"
