definitions:
  dbmodel.Coordinate:
    properties:
      lat:
        type: number
      long:
        type: number
    type: object
  dbmodel.DeviceType:
    enum:
    - computer
    - camera
    - printer
    type: string
    x-enum-varnames:
    - DeviceTypeComputer
    - DeviceTypeCamera
    - DeviceTypePrinter
  entity.Device:
    properties:
      angle:
        type: number
      camera_connection_url:
        type: string
      created_at:
        type: string
      id:
        type: string
      ip:
        type: string
      is_active:
        type: boolean
      layer_id:
        description: ??
        type: string
      location_x:
        type: number
      location_y:
        type: number
      mac_address:
        type: string
      name:
        type: string
      type:
        $ref: '#/definitions/entity.DeviceType'
      updated_at:
        type: string
    type: object
  entity.DeviceType:
    enum:
    - computer
    - camera
    - printer
    type: string
    x-enum-varnames:
    - Computer
    - Camera
    - Printer
  entity.Layer:
    properties:
      angle:
        type: number
      angles_coordinates:
        items:
          $ref: '#/definitions/dbmodel.Coordinate'
        type: array
      created_at:
        type: string
      devices:
        items:
          $ref: '#/definitions/entity.Device'
        type: array
      floor_name:
        type: string
      id:
        type: string
      image:
        type: string
      object_id:
        type: string
      updated_at:
        type: string
    type: object
  entity.LoginInfo:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  entity.NewUser:
    properties:
      is_admin:
        type: boolean
      password:
        type: string
      username:
        type: string
    type: object
  entity.UserInfo:
    properties:
      id:
        type: string
      is_admin:
        type: boolean
      username:
        type: string
    type: object
  network.DeviceStatus:
    properties:
      ipAddress:
        type: string
      isActive:
        type: boolean
      macAddress:
        type: string
    type: object
  sledilka.CreateDevice:
    properties:
      angle:
        type: number
      camera_connection_url:
        type: string
      ip_address:
        type: string
      layer_id:
        type: string
      location_x:
        type: number
      location_y:
        type: number
      mac_address:
        type: string
      name:
        type: string
      type:
        $ref: '#/definitions/dbmodel.DeviceType'
    type: object
  sledilka.Device:
    properties:
      angle:
        type: number
      camera_connection_url:
        type: string
      created_at:
        type: string
      id:
        type: string
      ip:
        type: string
      is_active:
        type: boolean
      layer_id:
        description: ??
        type: string
      location_x:
        type: number
      location_y:
        type: number
      mac_address:
        type: string
      name:
        type: string
      type:
        $ref: '#/definitions/entity.DeviceType'
      updated_at:
        type: string
    type: object
  sledilka.Layer:
    properties:
      angle:
        type: number
      angles_coordinates:
        items:
          $ref: '#/definitions/dbmodel.Coordinate'
        type: array
      created_at:
        type: string
      devices:
        items:
          $ref: '#/definitions/entity.Device'
        type: array
      floor_name:
        type: string
      id:
        type: string
      image:
        type: string
      object_id:
        type: string
      updated_at:
        type: string
    type: object
  sledilka.NewLayer:
    properties:
      angle:
        type: number
      angles_coordinates:
        items:
          $ref: '#/definitions/dbmodel.Coordinate'
        type: array
      floor_name:
        type: string
      image:
        type: string
    type: object
  sledilka.NewObject:
    properties:
      address:
        type: string
      description:
        type: string
      lat:
        type: number
      long:
        type: number
      name:
        type: string
    type: object
  sledilka.Object:
    properties:
      address:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      lat:
        type: number
      layers:
        items:
          $ref: '#/definitions/entity.Layer'
        type: array
      long:
        type: number
      name:
        type: string
      updated_at:
        type: string
    type: object
  sledilka.UpdateDevice:
    properties:
      angle:
        type: number
      camera_connection_url:
        type: string
      ip:
        type: string
      layer_id:
        description: ??
        type: string
      location_x:
        type: number
      location_y:
        type: number
      mac_address:
        type: string
      name:
        type: string
      type:
        $ref: '#/definitions/entity.DeviceType'
    type: object
  timestamppb.Timestamp:
    properties:
      nanos:
        description: |-
          Non-negative fractions of a second at nanosecond resolution. Negative
          second values with fractions must still have non-negative nanos values
          that count forward in time. Must be from 0 to 999,999,999
          inclusive.
        type: integer
      seconds:
        description: |-
          Represents seconds of UTC time since Unix epoch
          1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
          9999-12-31T23:59:59Z inclusive.
        type: integer
    type: object
  tokener.CreateTokenResponse:
    properties:
      access_token:
        type: string
      expires_at:
        $ref: '#/definitions/timestamppb.Timestamp'
      refresh_token:
        type: string
    type: object
  tokener.RefreshTokenResponse:
    properties:
      access_token:
        type: string
      expires_at:
        $ref: '#/definitions/timestamppb.Timestamp'
      refresh_token:
        type: string
    type: object
host: 192.168.1.75:8081
info:
  contact: {}
  description: API for Sledilka service
  termsOfService: http://swagger.io/terms/
  title: Sledilka API
  version: "1.0"
paths:
  /devices:
    post:
      consumes:
      - application/json
      parameters:
      - description: Новый девайс
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/sledilka.CreateDevice'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sledilka.Device'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Создать девайс
      tags:
      - devices
  /devices/{id}:
    patch:
      consumes:
      - application/json
      parameters:
      - description: Измененный девайс
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/sledilka.UpdateDevice'
      - description: Device ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Device'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Изменить девайс
      tags:
      - devices
  /images:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: картинка слоя
        in: formData
        name: request
        required: true
        type: file
      responses:
        "200":
          description: OK
      summary: Upload File
      tags:
      - images
  /images/{file}:
    get:
      parameters:
      - description: file name with extension
        in: path
        name: file
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: Load File
      tags:
      - images
  /isLowLight/{id}:
    get:
      parameters:
      - description: Device ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "500":
          description: Internal Server Error
      summary: получить трансляцию
      tags:
      - isLowLight
  /network:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/network.DeviceStatus'
            type: array
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Получить список адресов в сети
      tags:
      - networking
  /new:
    post:
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Новые сущности
      tags:
      - new
  /objects:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/sledilka.Object'
            type: array
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Возвращает все объекты
      tags:
      - objects
    post:
      consumes:
      - application/json
      parameters:
      - description: Новый объект
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/sledilka.NewObject'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sledilka.Object'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Создать объект
      tags:
      - objects
  /objects/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sledilka.Object'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Объект по id
      tags:
      - objects
    patch:
      consumes:
      - application/json
      parameters:
      - description: Измененный Объект
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/sledilka.NewObject'
      - description: Object ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sledilka.Object'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Изменить объект
      tags:
      - objects
  /objects/{id}/layers:
    post:
      consumes:
      - application/json
      parameters:
      - description: Новый слой
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/sledilka.NewLayer'
      - description: Object ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sledilka.Layer'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Создать слой
      tags:
      - layers
  /objects/{object_id}/layers/{id}:
    get:
      parameters:
      - description: Layer ID
        in: path
        name: id
        required: true
        type: string
      - description: Object ID
        in: path
        name: object_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sledilka.Layer'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Получить слой
      tags:
      - layers
    patch:
      consumes:
      - application/json
      parameters:
      - description: Измененный слой
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/sledilka.NewLayer'
      - description: Object ID
        in: path
        name: object_id
        required: true
        type: string
      - description: Layer ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sledilka.Layer'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Изменить слой
      tags:
      - layers
  /refresh:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tokener.RefreshTokenResponse'
        "500":
          description: Internal Server Error
      summary: Обновить токен
      tags:
      - token
  /stream/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Device ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "500":
          description: Internal Server Error
      summary: получить трансляцию
      tags:
      - stream
  /subscribe-network:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/network.DeviceStatus'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Подписаться на обновления из сети. WebSocket
      tags:
      - networking
  /token:
    post:
      consumes:
      - application/json
      parameters:
      - description: Регистрационная информация
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.LoginInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tokener.CreateTokenResponse'
        "500":
          description: Internal Server Error
      summary: Авторизоваться
      tags:
      - token
  /user:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.UserInfo'
            type: array
        "500":
          description: Internal Server Error
      summary: Получить список пользователей
      tags:
      - user
    post:
      consumes:
      - application/json
      parameters:
      - description: Регистрационная информация
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.NewUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.UserInfo'
        "500":
          description: Internal Server Error
      summary: Зарегистрировать
      tags:
      - user
  /user/{id}:
    get:
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.UserInfo'
        "500":
          description: Internal Server Error
      summary: Получить информацию о пользователе по id
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Auth-Token
    scopes:
      admin: Grants read and write access to administrative information
      write: Grants write access
    type: apiKey
swagger: "2.0"
