definitions:
  backend_internal_dbmodel.Coordinate:
    properties:
      lat:
        type: number
      long:
        type: number
    type: object
  backend_internal_dbmodel.DeviceType:
    enum:
    - computer
    - camera
    - printer
    - scanner
    - phone
    - smart_bulb
    - smart_fridge
    - custom
    - raspberry_pi
    - machine_tool
    type: string
    x-enum-varnames:
    - DeviceTypeComputer
    - DeviceTypeCamera
    - DeviceTypePrinter
    - DeviceTypeScanner
    - DeviceTypePhone
    - DeviceTypeSmartBulb
    - DeviceTypeSmartFridge
    - DeviceTypeCustom
    - DeviceTypeRaspberryPi
    - DeviceTypeMachineTool
  backend_internal_entity.CreateDevice:
    properties:
      angle:
        type: number
      camera_connection_url:
        type: string
      ip_address:
        type: string
      layer_id:
        type: string
      location_x:
        type: number
      location_y:
        type: number
      mac_address:
        type: string
      name:
        type: string
      type:
        $ref: '#/definitions/backend_internal_dbmodel.DeviceType'
    type: object
  backend_internal_entity.Device:
    properties:
      angle:
        type: number
      camera_connection_url:
        type: string
      created_at:
        type: string
      id:
        type: string
      ip:
        type: string
      is_active:
        type: boolean
      layer_id:
        description: ??
        type: string
      location_x:
        type: number
      location_y:
        type: number
      mac_address:
        type: string
      name:
        type: string
      type:
        $ref: '#/definitions/backend_internal_entity.DeviceType'
      updated_at:
        type: string
    type: object
  backend_internal_entity.DeviceStatus:
    properties:
      ipAddress:
        type: string
      is_busy:
        type: boolean
      isActive:
        type: boolean
      macAddress:
        type: string
    type: object
  backend_internal_entity.DeviceType:
    enum:
    - computer
    - camera
    - printer
    type: string
    x-enum-varnames:
    - Computer
    - Camera
    - Printer
  backend_internal_entity.Layer:
    properties:
      angle:
        type: number
      angles_coordinates:
        items:
          $ref: '#/definitions/backend_internal_dbmodel.Coordinate'
        type: array
      created_at:
        type: string
      devices:
        items:
          $ref: '#/definitions/backend_internal_entity.Device'
        type: array
      floor_name:
        type: string
      id:
        type: string
      image:
        type: string
      object_id:
        type: string
      updated_at:
        type: string
    type: object
  backend_internal_entity.LoginInfo:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  backend_internal_entity.NewDevice:
    properties:
      angle:
        type: number
      camera_connection_url:
        type: string
      ip:
        type: string
      layer_id:
        description: ??
        type: string
      location_x:
        type: number
      location_y:
        type: number
      mac_address:
        type: string
      name:
        type: string
      type:
        $ref: '#/definitions/backend_internal_entity.DeviceType'
    type: object
  backend_internal_entity.NewLayer:
    properties:
      angle:
        type: number
      angles_coordinates:
        items:
          $ref: '#/definitions/backend_internal_dbmodel.Coordinate'
        type: array
      floor_name:
        type: string
      image:
        type: string
    type: object
  backend_internal_entity.NewObject:
    properties:
      address:
        type: string
      description:
        type: string
      lat:
        type: number
      long:
        type: number
      name:
        type: string
    type: object
  backend_internal_entity.NewUser:
    properties:
      is_admin:
        type: boolean
      password:
        type: string
      username:
        type: string
    type: object
  backend_internal_entity.Object:
    properties:
      address:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      lat:
        type: number
      layers:
        items:
          $ref: '#/definitions/backend_internal_entity.Layer'
        type: array
      long:
        type: number
      name:
        type: string
      updated_at:
        type: string
    type: object
  backend_internal_entity.UserInfo:
    properties:
      id:
        type: string
      is_admin:
        type: boolean
      username:
        type: string
    type: object
  backend_internal_tokener.CreateTokenResponse:
    properties:
      access_token:
        type: string
      expires_at:
        $ref: '#/definitions/timestamppb.Timestamp'
      refresh_token:
        type: string
    type: object
  backend_internal_tokener.RefreshTokenResponse:
    properties:
      access_token:
        type: string
      expires_at:
        $ref: '#/definitions/timestamppb.Timestamp'
      refresh_token:
        type: string
    type: object
  timestamppb.Timestamp:
    properties:
      nanos:
        description: |-
          Non-negative fractions of a second at nanosecond resolution. Negative
          second values with fractions must still have non-negative nanos values
          that count forward in time. Must be from 0 to 999,999,999
          inclusive.
        type: integer
      seconds:
        description: |-
          Represents seconds of UTC time since Unix epoch
          1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
          9999-12-31T23:59:59Z inclusive.
        type: integer
    type: object
host: 0.0.0.0:8081
info:
  contact: {}
  description: API for Sledilka service
  termsOfService: http://swagger.io/terms/
  title: Sledilka API
  version: "1.0"
paths:
  /devices:
    post:
      consumes:
      - application/json
      parameters:
      - description: Новый девайс
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/backend_internal_entity.CreateDevice'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backend_internal_entity.Device'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Создать девайс
      tags:
      - devices
  /devices/{id}:
    patch:
      consumes:
      - application/json
      parameters:
      - description: Измененный девайс
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/backend_internal_entity.NewDevice'
      - description: Device ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backend_internal_entity.Device'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Изменить девайс
      tags:
      - devices
  /images:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: картинка слоя
        in: formData
        name: request
        required: true
        type: file
      responses:
        "200":
          description: OK
      summary: Upload File
      tags:
      - images
  /images/{file}:
    get:
      parameters:
      - description: file name with extension
        in: path
        name: file
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: Load File
      tags:
      - images
  /isLowLight/{id}:
    get:
      parameters:
      - description: Device ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "500":
          description: Internal Server Error
      summary: получить трансляцию
      tags:
      - isLowLight
  /network:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/backend_internal_entity.DeviceStatus'
            type: array
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Получить список адресов в сети
      tags:
      - networking
  /new:
    post:
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Новые сущности
      tags:
      - new
  /objects:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/backend_internal_entity.Object'
            type: array
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Возвращает все объекты
      tags:
      - objects
    post:
      consumes:
      - application/json
      parameters:
      - description: Новый объект
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/backend_internal_entity.NewObject'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backend_internal_entity.Object'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Создать объект
      tags:
      - objects
  /objects/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backend_internal_entity.Object'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Объект по id
      tags:
      - objects
    patch:
      consumes:
      - application/json
      parameters:
      - description: Измененный Объект
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/backend_internal_entity.NewObject'
      - description: Object ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backend_internal_entity.Object'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Изменить объект
      tags:
      - objects
  /objects/{id}/layers:
    post:
      consumes:
      - application/json
      parameters:
      - description: Новый слой
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/backend_internal_entity.NewLayer'
      - description: Object ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backend_internal_entity.Layer'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Создать слой
      tags:
      - layers
  /objects/{object_id}/layers/{id}:
    get:
      parameters:
      - description: Layer ID
        in: path
        name: id
        required: true
        type: string
      - description: Object ID
        in: path
        name: object_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backend_internal_entity.Layer'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Получить слой
      tags:
      - layers
    patch:
      consumes:
      - application/json
      parameters:
      - description: Измененный слой
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/backend_internal_entity.NewLayer'
      - description: Object ID
        in: path
        name: object_id
        required: true
        type: string
      - description: Layer ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backend_internal_entity.Layer'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Изменить слой
      tags:
      - layers
  /refresh:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backend_internal_tokener.RefreshTokenResponse'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Обновить токен
      tags:
      - token
  /stream/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Device ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "500":
          description: Internal Server Error
      summary: получить трансляцию
      tags:
      - stream
  /subscribe-network:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backend_internal_entity.Device'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Подписаться на обновления из сети. WebSocket
      tags:
      - networking
  /token:
    post:
      consumes:
      - application/json
      parameters:
      - description: Регистрационная информация
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/backend_internal_entity.LoginInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backend_internal_tokener.CreateTokenResponse'
        "500":
          description: Internal Server Error
      summary: Авторизоваться
      tags:
      - token
  /user:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/backend_internal_entity.UserInfo'
            type: array
        "500":
          description: Internal Server Error
      summary: Получить список пользователей
      tags:
      - user
    post:
      consumes:
      - application/json
      parameters:
      - description: Регистрационная информация
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/backend_internal_entity.NewUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backend_internal_entity.UserInfo'
        "500":
          description: Internal Server Error
      summary: Зарегистрировать
      tags:
      - user
  /user/{id}:
    get:
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backend_internal_entity.UserInfo'
        "500":
          description: Internal Server Error
      summary: Получить информацию о пользователе по id
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Auth-Token
    scopes:
      admin: Grants read and write access to administrative information
      write: Grants write access
    type: apiKey
swagger: "2.0"
