definitions:
  entity.Announcement:
    properties:
      createdAt:
        type: integer
      description:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
  entity.NewAnnouncement:
    properties:
      description:
        type: string
      title:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: API for Sledilka service
  termsOfService: http://swagger.io/terms/
  title: Sledilka API
  version: "1.0"
paths:
  /announcement:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID анонса на удаление
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Announcement'
        "500":
          description: Internal Server Error
      summary: Удаляет анонс
      tags:
      - announcements
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Announcement'
            type: array
        "500":
          description: Internal Server Error
      summary: Возвращает анонсы
      tags:
      - announcements
    post:
      consumes:
      - application/json
      parameters:
      - description: тело нового запроса
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.NewAnnouncement'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Announcement'
        "500":
          description: Internal Server Error
      summary: Создает анонс
      tags:
      - announcements
swagger: "2.0"
