name: run-project-lints
on: [push]
jobs:
  lint-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 16

      - name: clean cache
        run: npm cache clean --force

      - name: Install deps
        working-directory: ./frontend
        run: npm ci

      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main

  test-backend:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1

        - name: Setup Go environment
          uses: actions/setup-go@v4.1.0
          with:
            cache-dependency-path: backend/go.sum
            go-version-file: backend/go.mod

        - name: Run Tests
          working-directory: ./backend
          run: go test

  build-frontend:
    runs-on: ubuntu-latest
    needs: [lint-frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 16

      - name: clean cache
        run: npm cache clean --force

      - name: Install deps
        working-directory: ./frontend
        run: npm ci

