name: run-project-lints
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install deps
        working-directory: ./frontend
        run: npm i
      - name: Check file existence
        working-directory: ./frontend
        run: ls -la
      - name: Lint frontend
        working-directory: ./frontend
        run: npm run lint

