name: run-project-lints
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: actions/checkout@v4.1.1
      - name: CD in frontend
        run: cd frontend
      - name: Install deps
        run: npm ci
      - name: Lint frontend
        run: npm run lint
         
